[[databases]]
location = "ensembldb.ensembl.org"
port="3306"
db_user="anonymous"

[[databases.species]]
db_name="homo_sapiens_core_106_38"
species_name="homo_sapiens"

[[databases.species]]
db_name="mus_musculus_core_106_39"
species_name="mus_musculus"

[[databases.tables]]
table_name = "gene"
query = '''
SELECT distinct g.gene_id as gene_id, g.stable_id as gene_stable_id, g.version as gene_stable_id_version, sr.name as gene_chr, g.seq_region_start as gene_start, g.seq_region_end as gene_end, g.biotype as gene_biotype, x.dbprimary_acc as gene_symbol_id, x.display_label as gene_symbol, ct.stable_id as canonical_transcript_stable_id, ct.version as canonical_transcript_stable_id_version, ct.biotype as canonical_transcript_biotype
FROM gene g
JOIN seq_region sr using (seq_region_id)
JOIN coord_system cs using (coord_system_id)
LEFT JOIN xref x on (g.display_xref_id = x.xref_id)
JOIN gene_attrib ga on (g.gene_id = ga.gene_id)
JOIN transcript ct on (g.canonical_transcript_id = ct.transcript_id)
JOIN meta m on (cs.species_id = m.species_id and m.meta_key = "species.production_name")
WHERE g.biotype <> "LRG_gene"
AND m.meta_value = %(species_name)s
'''

[[databases.tables]]
table_name = "transcript"
query = '''
SELECT
t.transcript_id as transcript_id,
t.stable_id as transcript_stable_id,
t.version as transcript_stable_id_version,
sr.name as transcript_chr,
t.seq_region_start as transcript_start,
t.seq_region_end as transcript_end,
t.biotype as transcript_biotype,
x.dbprimary_acc as transcript_symbol_id,
x.display_label as transcript_symbol,
g.stable_id as gene_stable_id,
g.version as gene_stable_id_version,
g.biotype as gene_biotype,
x.dbprimary_acc as gene_symbol_id,
x.display_label as gene_symbol
FROM transcript t
JOIN seq_region sr ON (t.seq_region_id = sr.seq_region_id)
JOIN coord_system cs ON (sr.coord_system_id = cs.coord_system_id)
LEFT JOIN xref x on (t.display_xref_id = x.xref_id)
JOIN gene g on (t.gene_id = g.gene_id)
LEFT JOIN xref xg on (g.display_xref_id = x.xref_id)
JOIN meta m on (cs.species_id = m.species_id and m.meta_key = "species.production_name")
WHERE g.biotype <> "LRG_gene"
AND m.meta_value = %(species_name)s
'''

[[databases.tables]]
table_name = "translation"
query = '''
SELECT
tr.translation_id as translation_id,
tr.stable_id as translation_stable_id,
tr.version as translation_stable_id_version,
t.stable_id as transcript_stable_id,
t.version as transcript_stable_id_version,
t.biotype as transcript_biotype
FROM translation tr
JOIN transcript t on (tr.transcript_id = t.transcript_id)
JOIN gene g on (t.gene_id = t.gene_id)
JOIN seq_region sr ON (t.seq_region_id = sr.seq_region_id)
JOIN coord_system cs ON (sr.coord_system_id = cs.coord_system_id)
JOIN meta m on (cs.species_id = m.species_id and m.meta_key = "species.production_name")
WHERE g.biotype <> "LRG_gene"
AND m.meta_value = %(species_name)s
'''

[[databases.tables]]
table_name = "protein_domains"
query = '''
SELECT
tr.translation_id as translation_id,
tr.stable_id as translation_stable_id,
tr.version as translation_stable_id_version,
pf.hit_name as protein_feature_name,
pf.seq_start as translation_hit_start,
pf.seq_end as translation_hit_end,
pf.hit_start as protein_feature_start,
pf.hit_end as protein_feature_end,
ip.interpro_ac as protein_feature_interpro,
pf.score as protein_feature_score,
pf.evalue as protein_feature_evalue,
pf.perc_ident as protein_feature_percentage_identity,
pf.hit_description as protein_feature_description
FROM translation tr
JOIN protein_feature pf ON (tr.translation_id = pf.translation_id)
JOIN interpro ip ON (pf.hit_name = ip.id)
JOIN transcript t on (tr.transcript_id = t.transcript_id)
JOIN gene g on (t.gene_id = t.gene_id)
JOIN seq_region sr ON (t.seq_region_id = sr.seq_region_id)
JOIN coord_system cs ON (sr.coord_system_id = cs.coord_system_id)
JOIN meta m on (cs.species_id = m.species_id and m.meta_key = "species.production_name")
WHERE g.biotype <> "LRG_gene"
AND m.meta_value = %(species_name)s
'''

[[databases.tables]]
table_name = "gene_xrefs"
query = '''
SELECT
g.stable_id as gene_stable_id,
g.version as gene_stable_id_version,
x.dbprimary_acc as gene_xref_accession,
x.version as gene_xref_version,
x.display_label as gene_xref_display,
x.description as gene_xref_description,
edb.db_name as gene_xref_database
FROM gene g
JOIN object_xref ox on (g.gene_id = ox.ensembl_id and ox.ensembl_object_type = 'Gene')
JOIN xref x on (ox.xref_id = x.xref_id)
JOIN external_db edb ON (x.external_db_id = edb.external_db_id)
JOIN seq_region sr ON (g.seq_region_id = sr.seq_region_id)
JOIN coord_system cs ON (sr.coord_system_id = cs.coord_system_id)
JOIN meta m on (cs.species_id = m.species_id and m.meta_key = "species.production_name")
WHERE g.biotype <> "LRG_gene"
AND m.meta_value = %(species_name)s
'''

[[databases.tables]]
table_name = "transcript_xrefs"
query = '''
SELECT
t.stable_id as transcript_stable_id,
t.version as transcript_stable_id_version,
x.dbprimary_acc as transcript_xref_accession,
x.version as transcript_xref_version,
x.display_label as transcript_xref_display,
x.description as transcript_xref_description,
edb.db_name as transcript_xref_database
FROM gene g
JOIN transcript t on (g.gene_id = t.gene_id)
JOIN object_xref ox on (t.transcript_id = ox.ensembl_id and ox.ensembl_object_type = 'Transcript')
JOIN xref x on (ox.xref_id = x.xref_id)
JOIN external_db edb ON (x.external_db_id = edb.external_db_id)
JOIN seq_region sr ON (g.seq_region_id = sr.seq_region_id)
JOIN coord_system cs ON (sr.coord_system_id = cs.coord_system_id)
JOIN meta m on (cs.species_id = m.species_id and m.meta_key = "species.production_name")
WHERE g.biotype <> "LRG_gene"
AND m.meta_value = %(species_name)s
'''

[[databases.tables]]
table_name = "translation__xrefs"
query = '''
SELECT
tr.stable_id as translation_stable_id,
tr.version as translation_stable_id_version,
x.dbprimary_acc as translation_xref_accession,
x.version as translation_xref_version,
x.display_label as translation_xref_display,
x.description as translation_xref_description,
edb.db_name as translation_xref_database
FROM gene g
JOIN transcript t on (g.gene_id = t.gene_id)
JOIN translation tr on (t.transcript_id = tr.transcript_id)
JOIN object_xref ox on (tr.translation_id = ox.ensembl_id and ox.ensembl_object_type = 'Translation')
JOIN xref x on (ox.xref_id = x.xref_id)
JOIN external_db edb ON (x.external_db_id = edb.external_db_id)
JOIN seq_region sr ON (g.seq_region_id = sr.seq_region_id)
JOIN coord_system cs ON (sr.coord_system_id = cs.coord_system_id)
JOIN meta m on (cs.species_id = m.species_id and m.meta_key = "species.production_name")
WHERE g.biotype <> "LRG_gene"
AND m.meta_value = 'homo_sapiens'
AND m.meta_value = %(species_name)s
'''
