[[databases]]
location = "ensembldb.ensembl.org"
port="3306"
DB_USER="anonymous"
[[databases.species]]
DB_name="homo_sapiens_core_106_38"
species_name="homo_sapiens"
[[databases.species]]
DB_name="mus_musculus_core_106_39"
species_name="mus_musculus"
[[databases.tables]]
table_name = "gene"
query = '''
SELECT distinct g.gene_id as gene_id, g.stable_id as gene_stable_id, g.version as gene_stable_id_version, sr.name as chr, g.seq_region_start as gene_start, g.seq_region_end as gene_end, g.biotype as gene_biotype, x.dbprimary_acc as gene_symbol_id, x.display_label as gene_symbol, ct.stable_id as canonical_transcript_stable_id, ct.version as canonical_transcript_stable_id_version, ct.biotype as canonical_transcript_biotype
FROM gene g
JOIN seq_region sr using (seq_region_id)
JOIN coord_system cs using (coord_system_id)
JOIN xref x on (g.display_xref_id = x.xref_id)
JOIN gene_attrib ga on (g.gene_id = ga.gene_id)
JOIN transcript ct on (g.canonical_transcript_id = ct.transcript_id)
JOIN meta m on (cs.species_id = m.species_id and m.meta_key = "species.production_name")
WHERE g.biotype <> "LRG_gene"
AND m.meta_value = %(species_name)s
'''